/* eslint-disable prettier/prettier */
/**
 * Generated by pullcode v1.2.1.
 * You can edit it as your need.
 */
import { KNOW_API_PREFIX } from "@/constant/constant";
import { customTransform, VAxios } from "@/httputil/Axios";
import { merge } from "lodash-es";
const defaultOptions = {
    requestOptions: {
        apiUrl: "", // same as baseUrl
        urlPrefix: KNOW_API_PREFIX,
    },
    transform: customTransform,
};
export class BizService extends VAxios {
    constructor(options) {
        super(merge(defaultOptions, options || {}));
    }
}
export default BizService;
