/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module List
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import qs from "qs";
import BizService from "./BizService";
import type { GetListReq, GetListResp } from "./types";

export class ListService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * GET /list
   *
   * @param req
   * @returns Promise<GetListResp>
   */
  getList(params: { req: GetListReq }): Promise<GetListResp> {
    return this.getAxios().get(`/list`, {
      params: {
        req: params.req,
      },
      paramsSerializer: (params) => qs.stringify(params),
    });
  }
}

export default ListService;

export function createListService(opt?: Partial<CreateAxiosOptions>) {
  return new ListService(opt);
}

export const listService = createListService();
