/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module List
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import BizService from "./BizService";
import type { GetListResp } from "./types";

export class ListService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * GET /list
   *
   * @returns Promise<GetListResp>
   */
  getList(): Promise<GetListResp> {
    return this.getAxios().get(`/list`, {});
  }
}

export default ListService;

export function createListService(opt?: Partial<CreateAxiosOptions>) {
  return new ListService(opt);
}

export const listService = createListService();
