/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module Query
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import qs from "qs";
import BizService from "./BizService";
import type { GetQueryResp, QueryReq } from "./types";

export class QueryService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * GET /query
   *
   * @param req
   * @returns Promise<GetQueryResp>
   */
  getQuery(params: { req: QueryReq }): Promise<GetQueryResp> {
    return this.getAxios().get(`/query`, {
      params: {
        req: params.req,
      },
      paramsSerializer: (params) => qs.stringify(params),
    });
  }
}

export default QueryService;

export function createQueryService(opt?: Partial<CreateAxiosOptions>) {
  return new QueryService(opt);
}

export const queryService = createQueryService();
