/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-empty-interface */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module types
 */

export interface FileDTO {
  content: string;
  id: number;
  path: string;
}

export interface GddUser {
  dept: string;
  id: number;
  name: string;
  phone: string;
}

export interface GetListReq {
  /**
   * 多个值用英文逗号拼接
   */
  file_id: string;
  with_content: boolean;
}

export interface GetListResp {
  data: FileDTO[];
}

export interface GetQueryResp {
  data: QueryResult[];
}

/**
 * Page result wrapper
 */
export interface Page {
  first: boolean;
  items: any[];
  last: boolean;
  max_page: number;
  page: number;
  size: number;
  total: number;
  total_pages: number;
  visible: number;
}

/**
 * Parameter struct
 */
export interface Parameter {
  fields: string;
  filters: string;
  order: string;
  page: number;
  size: number;
  sort: string;
}

export interface QueryReq {
  text: string;
  top: number;
}

export interface QueryResult {
  content: string;
  id: string;
  similarity: string;
}

export interface UploadReq {
  file: Blob;
}

export interface UploadResp {
  data: UploadResult;
}

export interface UploadResult {
  id: number;
}
