/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module Upload
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import BizService from "./BizService";
import type { UploadResp } from "./types";

export class UploadService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * POST /upload
   *
   * @param formData
   * @returns Promise<UploadResp>
   */
  postUpload(formData: FormData): Promise<UploadResp> {
    return this.getAxios().post(`/upload`, formData, {});
  }
}

export default UploadService;

export function createUploadService(opt?: Partial<CreateAxiosOptions>) {
  return new UploadService(opt);
}

export const uploadService = createUploadService();
