/**
* Generated by go-doudou v2.5.8.
* You can edit it as your need.
 */
package service

import (
	"context"
	"go-doudou-rag/module-auth/dto"
	"go-doudou-rag/module-auth/internal/model"
)

//go:generate go-doudou svc http --case snake

type ModuleAuth interface {
	// PostLogin @role(guest)
	PostLogin(ctx context.Context, req dto.LoginReq) (data dto.LoginResp, err error)
	GetMe(ctx context.Context) (data *model.User, err error)
}
