/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
 */
package httpsrv

import (
	"context"
	service "go-doudou-rag/module-chat"
	"go-doudou-rag/module-chat/dto"
	"net/http"

	"github.com/bytedance/sonic"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

var json = sonic.ConfigDefault

type ModuleChatHandlerImpl struct {
	moduleChat service.ModuleChat
}

func (receiver *ModuleChatHandlerImpl) PostUser(_writer http.ResponseWriter, _req *http.Request) {
	var (
		ctx  context.Context
		user dto.GddUser
		data dto.GddUser
		err  error
	)
	ctx = _req.Context()
	if _err := json.NewDecoder(_req.Body).Decode(&user); _err != nil {
		rest.HandleBadRequestErr(_err)
	} else {
		if _err := rest.ValidateStruct(user); _err != nil {
			rest.HandleBadRequestErr(_err)
		}
	}
	data, err = receiver.moduleChat.PostUser(
		ctx,
		user,
	)
	if err != nil {
		panic(err)
	}
	_writer.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if _err := json.NewEncoder(_writer).Encode(struct {
		Data dto.GddUser `json:"data"`
	}{
		Data: data,
	}); _err != nil {
		rest.HandleInternalServerError(_err)
	}
}
func (receiver *ModuleChatHandlerImpl) PutUser(_writer http.ResponseWriter, _req *http.Request) {
	var (
		ctx  context.Context
		user dto.GddUser
		re   error
	)
	ctx = _req.Context()
	if _err := json.NewDecoder(_req.Body).Decode(&user); _err != nil {
		rest.HandleBadRequestErr(_err)
	} else {
		if _err := rest.ValidateStruct(user); _err != nil {
			rest.HandleBadRequestErr(_err)
		}
	}
	re = receiver.moduleChat.PutUser(
		ctx,
		user,
	)
	if re != nil {
		panic(re)
	}
	_writer.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if _err := json.NewEncoder(_writer).Encode(struct {
	}{}); _err != nil {
		rest.HandleInternalServerError(_err)
	}
}
func (receiver *ModuleChatHandlerImpl) DeleteUser(_writer http.ResponseWriter, _req *http.Request) {
	var (
		ctx  context.Context
		user dto.GddUser
		re   error
	)
	ctx = _req.Context()
	if _err := json.NewDecoder(_req.Body).Decode(&user); _err != nil {
		rest.HandleBadRequestErr(_err)
	} else {
		if _err := rest.ValidateStruct(user); _err != nil {
			rest.HandleBadRequestErr(_err)
		}
	}
	re = receiver.moduleChat.DeleteUser(
		ctx,
		user,
	)
	if re != nil {
		panic(re)
	}
	_writer.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if _err := json.NewEncoder(_writer).Encode(struct {
	}{}); _err != nil {
		rest.HandleInternalServerError(_err)
	}
}
func (receiver *ModuleChatHandlerImpl) GetUsers(_writer http.ResponseWriter, _req *http.Request) {
	var (
		ctx       context.Context
		parameter dto.Parameter
		data      dto.Page
		err       error
	)
	ctx = _req.Context()
	if _err := _req.ParseForm(); _err != nil {
		rest.HandleBadRequestErr(_err)
	}
	if _err := rest.DecodeForm(&parameter, _req.Form); _err != nil {
		rest.HandleBadRequestErr(_err)
	} else {
		if _err := rest.ValidateStruct(parameter); _err != nil {
			rest.HandleBadRequestErr(_err)
		}
	}
	data, err = receiver.moduleChat.GetUsers(
		ctx,
		parameter,
	)
	if err != nil {
		panic(err)
	}
	_writer.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if _err := json.NewEncoder(_writer).Encode(struct {
		Data dto.Page `json:"data"`
	}{
		Data: data,
	}); _err != nil {
		rest.HandleInternalServerError(_err)
	}
}

func NewModuleChatHandler(moduleChat service.ModuleChat) ModuleChatHandler {
	return &ModuleChatHandlerImpl{
		moduleChat,
	}
}
