/**
* Generated by go-doudou v2.5.10.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type ModuleChatHandler interface {
	Chat(w http.ResponseWriter, r *http.Request)
}

func Routes(handler ModuleChatHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "Chat",
			Method:      "POST",
			Pattern:     "/chat",
			HandlerFunc: handler.Chat,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}

func init() {
	framework.RegisterAnnotationStore(RouteAnnotationStore)
}
