/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
 */
package httpsrv

import (
	"go-doudou-rag/module-chat/contextutil"
	"net/http"
)

func InjectResponseWriter(inner http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		r = r.WithContext(contextutil.NewResponseWriterContext(r.Context(), w))
		inner.ServeHTTP(w, r)
	})
}
