/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module Chat
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import BizService from "./BizService";
import type { ChatRequest, ChatResp } from "./types";

export class ChatService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * POST /chat
   *
   * @param payload
   * @returns Promise<ChatResp>
   */
  postChat(payload: ChatRequest): Promise<ChatResp> {
    return this.getAxios().post(`/chat`, payload, {});
  }
}

export default ChatService;

export function createChatService(opt?: Partial<CreateAxiosOptions>) {
  return new ChatService(opt);
}

export const chatService = createChatService();
