/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-empty-interface */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module types
 */

export interface ChatRequest {
  /**
   * 多个值英文逗号拼接
   */
  file_id: string;
  prompt: string;
}

export interface ChatResp {}

export interface ChatResponse {
  content: string;
  request_id: string;
  type: string;
}

export interface GddUser {
  dept: string;
  id: number;
  name: string;
  phone: string;
}

/**
 * Page result wrapper
 */
export interface Page {
  first: boolean;
  items: any[];
  last: boolean;
  max_page: number;
  page: number;
  size: number;
  total: number;
  total_pages: number;
  visible: number;
}

/**
 * Parameter struct
 */
export interface Parameter {
  fields: string;
  filters: string;
  order: string;
  page: number;
  size: number;
  sort: string;
}
