/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-empty-interface */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module types
 */
export {};
