/* eslint-disable prettier/prettier */
/**
 * Generated by pullcode v1.2.1.
 * You can edit it as your need.
 */
import { AUTH_API_PREFIX } from "@/constant/constant";
import { CreateAxiosOptions, customTransform, VAxios } from "@/httputil/Axios";
import { RequestOptions } from "@/types/axios";
import { merge } from "lodash-es";

const defaultOptions: CreateAxiosOptions = {
  requestOptions: {
    apiUrl: "", // same as baseUrl
    urlPrefix: AUTH_API_PREFIX,
  } as RequestOptions,
  transform: customTransform,
};

export class BizService extends VAxios {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(merge(defaultOptions, options || {}));
  }
}

export default BizService;
