/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module Login
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import BizService from "./BizService";
import type { LoginReq, PostLoginResp } from "./types";

export class LoginService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * POST /login
   *
   * PostLogin @role(guest)
   * @param payload
   * @returns Promise<PostLoginResp>
   */
  postLogin(payload: LoginReq): Promise<PostLoginResp> {
    return this.getAxios().post(`/login`, payload, {});
  }
}

export default LoginService;

export function createLoginService(opt?: Partial<CreateAxiosOptions>) {
  return new LoginService(opt);
}

export const loginService = createLoginService();
