/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module Me
 */
import { CreateAxiosOptions } from "@/httputil/axiosTransform";
import BizService from "./BizService";
import type { GetMeResp } from "./types";

export class MeService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * GET /me
   *
   * @returns Promise<GetMeResp>
   */
  getMe(): Promise<GetMeResp> {
    return this.getAxios().get(`/me`, {});
  }
}

export default MeService;

export function createMeService(opt?: Partial<CreateAxiosOptions>) {
  return new MeService(opt);
}

export const meService = createMeService();
