/**
* Generated by go-doudou v2.5.10.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type ModuleKnowledgeHandler interface {
	Upload(w http.ResponseWriter, r *http.Request)
	GetList(w http.ResponseWriter, r *http.Request)
	GetQuery(w http.ResponseWriter, r *http.Request)
}

func Routes(handler ModuleKnowledgeHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "Upload",
			Method:      "POST",
			Pattern:     "/upload",
			HandlerFunc: handler.Upload,
		},
		{
			Name:        "GetList",
			Method:      "GET",
			Pattern:     "/list",
			HandlerFunc: handler.GetList,
		},
		{
			Name:        "GetQuery",
			Method:      "GET",
			Pattern:     "/query",
			HandlerFunc: handler.GetQuery,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}

func init() {
	framework.RegisterAnnotationStore(RouteAnnotationStore)
}
