/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
*/
package main

import (
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
	service "go-doudou-rag/module-chat"
    "go-doudou-rag/module-chat/config"
	"go-doudou-rag/module-chat/transport/httpsrv"
)

func main() {
	conf := config.LoadFromEnv()
    svc := service.NewModuleChat(conf)
	handler := httpsrv.NewModuleChatHandler(svc)
	srv := rest.NewRestServer()
	srv.AddRoutes(httpsrv.Routes(handler))
	srv.AddRoutes(rest.DocRoutes(service.Oas))
	srv.Run()
}
