/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
 */
package plugin

import (
	service "go-doudou-rag/module-chat"
	"go-doudou-rag/module-chat/config"
	"go-doudou-rag/module-chat/frontend"
	"go-doudou-rag/module-chat/transport/httpsrv"
	"io/fs"
	"os"

	"github.com/unionj-cloud/go-doudou/v2/framework/grpcx"
	"github.com/unionj-cloud/go-doudou/v2/framework/plugin"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
	"github.com/unionj-cloud/toolkit/pipeconn"
	"github.com/unionj-cloud/toolkit/stringutils"
	"google.golang.org/grpc"
)

var _ plugin.ServicePlugin = (*ModuleChatPlugin)(nil)

type ModuleChatPlugin struct {
	grpcConns []*grpc.ClientConn
}

func (receiver *ModuleChatPlugin) Close() {
	for _, item := range receiver.grpcConns {
		item.Close()
	}
}

func (receiver *ModuleChatPlugin) GoDoudouServicePlugin() {

}

func (receiver *ModuleChatPlugin) GetName() string {
	name := os.Getenv("GDD_SERVICE_NAME")
	if stringutils.IsEmpty(name) {
		name = "cloud.unionj.ModuleChat"
	}
	return name
}

func (receiver *ModuleChatPlugin) Initialize(restServer *rest.RestServer, grpcServer *grpcx.GrpcServer, dialCtx pipeconn.DialContextFunc) {
	dist_storage, _ := fs.Sub(frontend.Dist, "dist")
	restServer.AddStaticResource(dist_storage, "")

	conf := config.LoadFromEnv()
	svc := service.NewModuleChat(conf)
	routes := httpsrv.Routes(httpsrv.NewModuleChatHandler(svc))
	restServer.GroupRoutes("/modulechat", routes, httpsrv.InjectResponseWriter)
	restServer.GroupRoutes("/modulechat", rest.DocRoutes(service.Oas))
}

func init() {
	plugin.RegisterServicePlugin(&ModuleChatPlugin{})
}
