/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
 */
package service

import (
	"context"
	"go-doudou-rag/module-chat/dto"
)

//go:generate go-doudou svc http --case snake

// ModuleChat
/*
curl -N -X POST 'http://localhost:6060/modulechat/chat' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUzODI3OTMsInVzZXJuYW1lIjoiYWRtaW4ifQ.cFzTNm6U3U18IZhBfLmL1HmCkHNvHrrsmcfH38Pa12g' \
--data '{
    "prompt": "最近杭州出台了什么经济相关的政策？"
}'
*/
type ModuleChat interface {
	Chat(ctx context.Context, req dto.ChatRequest) (err error)
}
