/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
 */
package service

import (
	"context"
	"go-doudou-rag/module-chat/config"
	"go-doudou-rag/module-chat/dto"

	"github.com/brianvoe/gofakeit/v6"
)

var _ ModuleChat = (*ModuleChatImpl)(nil)

type ModuleChatImpl struct {
	conf *config.Config
}

func (receiver *ModuleChatImpl) PostUser(ctx context.Context, user dto.GddUser) (data dto.GddUser, err error) {
	var _result struct {
		Data dto.GddUser
	}
	_ = gofakeit.Struct(&_result)
	return _result.Data, nil
}
func (receiver *ModuleChatImpl) PutUser(ctx context.Context, user dto.GddUser) (re error) {
	var _result struct {
	}
	_ = gofakeit.Struct(&_result)
	return nil
}
func (receiver *ModuleChatImpl) DeleteUser(ctx context.Context, user dto.GddUser) (re error) {
	var _result struct {
	}
	_ = gofakeit.Struct(&_result)
	return nil
}
func (receiver *ModuleChatImpl) GetUsers(ctx context.Context, parameter dto.Parameter) (data dto.Page, err error) {
	var _result struct {
		Data dto.Page
	}
	_ = gofakeit.Struct(&_result)
	return _result.Data, nil
}

func NewModuleChat(conf *config.Config) *ModuleChatImpl {
	return &ModuleChatImpl{
		conf: conf,
	}
}
