/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
*/
package config

import (
	"github.com/unionj-cloud/toolkit/envconfig"
	"github.com/unionj-cloud/go-doudou/v2/framework/config"
	"github.com/unionj-cloud/toolkit/zlogger"
)

var G_Config *Config

type Config struct {
	Biz struct {
		ApiSecret string `split_words:"true"`
	}
	config.Config
}

func init() {
	var conf Config
	err := envconfig.Process("modulechat", &conf)
	if err != nil {
		zlogger.Panic().Msgf("Error processing environment variables: %v", err)
	}
	G_Config = &conf
}

func LoadFromEnv() *Config {
	return G_Config
}
