/**
* Generated by go-doudou v2.5.10.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type ModuleAuthHandler interface {
	PostLogin(w http.ResponseWriter, r *http.Request)
	GetMe(w http.ResponseWriter, r *http.Request)
}

func Routes(handler ModuleAuthHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "PostLogin",
			Method:      "POST",
			Pattern:     "/login",
			HandlerFunc: handler.PostLogin,
		},
		{
			Name:        "GetMe",
			Method:      "GET",
			Pattern:     "/me",
			HandlerFunc: handler.GetMe,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{
	"PostLogin": {
		{
			Name: "@role",
			Params: []string{
				"guest",
			},
		},
	},
}

func init() {
	framework.RegisterAnnotationStore(RouteAnnotationStore)
}
